#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# ci_post_clone.sh — make an Xcode Cloud clone buildable.
#
# WHY THIS EXISTS
#   Xcode Cloud clones the repository and then expects to open a project. This
#   repository has none: `*.xcodeproj` is generated by xcodegen and gitignored.
#   Without this script the build fails at the very first step, before any of
#   the interesting ones.
#
#   Apple runs `ci_scripts/ci_post_clone.sh` after the clone and *before*
#   dependency resolution and the build, which is the only hook early enough to
#   create a project for the build to open. Note the ordering consequence
#   below: there is no SPM checkout yet when this runs.
#
#   The workflow in App Store Connect is configured against a *locally*
#   generated project — the setup wizard reads the scheme list off disk — so
#   run `make generate` before touching the wizard. What the wizard records is
#   only the project and scheme *names*, and this script reproduces both.
#
# WHAT IT DOES NOT DO
#   No signing, no certificate handling, no upload. Xcode Cloud owns all of
#   that; this script's whole job is to leave a clone looking like a working
#   tree after `make generate`.
#
# RUNNING IT BY HAND
#   It is safe to run locally — it is `make generate` plus a build number. The
#   `brew install` lines are the only part that will feel redundant.
#
# See docs/DEVELOPMENT-PLAN.md APP-25, and docs/CODEC2.md.

set -euo pipefail

note() { printf '\033[1m==>\033[0m %s\n' "$*"; }

# Apple runs this from `ci_scripts/`, not the repository root, and the paths in
# project.yml are all root-relative.
# CI_PRIMARY_REPOSITORY_PATH is Xcode Cloud's; the fallback is for a hand run.
cd "${CI_PRIMARY_REPOSITORY_PATH:-"$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"}"
note "working in $(pwd)"

# --------------------------------------------------------------------------
# Tools.
#
# Homebrew is present in the Xcode Cloud environment but nothing is installed
# in it. Auto-update costs a minute and buys nothing: the formula is pinned by
# nothing and wanted at whatever version is current.
# --------------------------------------------------------------------------
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

# cmake was here too until APP-31, only ever to build Codec2.xcframework.
for tool in xcodegen; do
    if command -v "$tool" >/dev/null 2>&1; then
        note "$tool already present"
    else
        note "installing $tool"
        brew install "$tool"
    fi
done

# --------------------------------------------------------------------------
# Build number.
#
# **APP-25 item 2.** `CFBundleVersion` is "1" in project.yml for both the app
# and the Live Activity extension, and App Store Connect refuses a build number
# it has already accepted. Xcode Cloud counts builds for us in CI_BUILD_NUMBER,
# so take it from there rather than from somebody remembering to bump a file.
#
# The two must move together: an extension whose CFBundleVersion disagrees with
# its host app is rejected at upload, not at build, which is a slow way to find
# out. Rewriting every occurrence in project.yml is what keeps them equal.
#
# CFBundleShortVersionString is deliberately *not* touched. That is the release
# version, it is a human decision, and it belongs in a commit.
# --------------------------------------------------------------------------
if [[ -n "${CI_BUILD_NUMBER:-}" ]]; then
    note "setting CFBundleVersion to ${CI_BUILD_NUMBER}"
    /usr/bin/sed -i '' \
        -E "s/^([[:space:]]*CFBundleVersion:).*/\1 \"${CI_BUILD_NUMBER}\"/" \
        project.yml
    grep -n 'CFBundleVersion:' project.yml
else
    note "CI_BUILD_NUMBER unset — leaving CFBundleVersion as committed"
fi

# --------------------------------------------------------------------------
# The project itself. Both schemes land in xcshareddata, so the workflow's
# chosen scheme — Currawong — resolves. CurrawongOnAir is generated too and is
# deliberately never selected: it transmits on air (APP-25 item 3).
# --------------------------------------------------------------------------
note "generating Currawong.xcodeproj"
xcodegen generate

# --------------------------------------------------------------------------
# Package.resolved.
#
# Xcode Cloud resolves dependencies with automatic resolution *disabled*: it
# insists on a resolved file and will not go and compute one. The message is
# "a resolved file is required when automatic dependency resolution is
# disabled", and it stops the build before the archive step. Running
# `xcodebuild -resolvePackageDependencies` here would not help — the same
# environment setting applies to our invocation.
#
# The file it wants lives inside the generated `.xcodeproj`, which is exactly
# what this repository does not commit. So the pin is committed *outside* the
# project, at `ci_scripts/Package.resolved`, and copied into place here — after
# `xcodegen generate`, because generation creates the workspace directory it
# goes in.
#
# Consequence worth knowing: this file, not `project.yml`'s `from:`, is what
# the cloud build actually builds. Change the dependency and the pin goes
# stale, and a stale pin fails the same way a missing one does. `make resolved`
# refreshes it; it belongs in the same commit as the `project.yml` change.
# --------------------------------------------------------------------------
PINNED=ci_scripts/Package.resolved
WORKSPACE_SWIFTPM=Currawong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm

if [[ -f "$PINNED" ]]; then
    note "installing $PINNED"
    mkdir -p "$WORKSPACE_SWIFTPM"
    cp "$PINNED" "$WORKSPACE_SWIFTPM/Package.resolved"
else
    echo "error: $PINNED is missing. Xcode Cloud cannot resolve without it." >&2
    echo "       Run \`make resolved\` and commit the result." >&2
    exit 1
fi

note "post-clone complete"
